variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TF_SERVICE_PROJECT_PATH: $CI_PROJECT_DIR/TF_Service_and_Tooling_Unity
  TF_PROJECT_PATH: $CI_PROJECT_DIR/TF_Application
  UNITY_HUB: "C:/Program Files/Unity Hub/Unity Hub.exe"

  TF_TFW_PATH: $CI_PROJECT_DIR/TF_Tooling_Web
  TF_TFU_PATH: $CI_PROJECT_DIR/TF_Service_and_Tooling_Unity/Assets/TouchFree/Tooling
  TF_SRV_PATH: $CI_PROJECT_DIR/TF_Service_and_Tooling_Unity/Assets/TouchFree/Service

  TF_TFU_VERSION: '1.0.0'
  TF_TFW_VERSION: '1.0.0'
  TOUCHFREE_VERSION: '2.1.0'

  TF_TOOLING_API_VERSION: '1.1.0'

stages:
  - build

TF_Service::dotNet::build:
  stage: build
  when: always
  script:
    - MSBuild.exe "$CI_PROJECT_DIR/TF_Service_dotNet/TouchFree Service/TouchFree Service.sln" /p:Configuration=Release /p:Platform=x64
    # Move the built wrapper to the root directory
    - mkdir ./Service_dotNet_Build
    - cp -r "$CI_PROJECT_DIR/TF_Service_dotNet/TouchFree Service/bin/x64/Release/netcoreapp3.1/*" ./Service_dotNet_Build

    # Sign the executable with the UltraLeap certificate
    - $cert=Get-ChildItem -Path Cert:\LocalMachine\My -CodeSigningCert
    - Set-AuthenticodeSignature -FilePath "$CI_PROJECT_DIR/Service_dotNet_Build/TouchFree Service.exe" -TimestampServer 'http://timestamp.comodoca.com/authenticode' -Certificate $cert
  artifacts:
    name: "TouchFree_Service_dotNet"
    paths:
    - ./Service_dotNet_Build/**
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10