variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test
  - package
  - deploy

.Always_Build:
  stage: build
  when: always
  timeout: 10m

.Always_Test:
  stage: test
  when: always
  timeout: 10m

.versions:
  before_script:
    # Get the TF Tooling for web version
    - set -Name TF_TOOLING_API_VERSION -Value "$((Select-String -Path ".\src\TouchFreeToolingTypes.ts" "public static readonly API_VERSION. string = '(.*)';" | Select-Object * -First 1).Matches.Groups[1].Value)"
    - set -Name TF_TFW_VERSION -Value "$((Select-String -Path ".\package.json" "  .version.. .(.*).," | Select-Object * -First 1).Matches.Groups[1].Value)"

build::bundle:
  extends: 
    - .Always_Build
    - .versions
  tags:
    - unity
    - win10
  script:
    # Get the TF Tooling for web version
    - set -Name TF_TOOLING_API_VERSION -Value "$((Select-String -Path ".\src\TouchFreeToolingTypes.ts" "public static readonly API_VERSION. string = '(.*)';" | Select-Object * -First 1).Matches.Groups[1].Value)"
    - set -Name TF_TFW_VERSION -Value "$((Select-String -Path ".\package.json" "  .version.. .(.*).," | Select-Object * -First 1).Matches.Groups[1].Value)"

    # Update Version.txt with latest information before packaging
    - python ./Scripts/UpdateVersionFile.py --path ${CI_PROJECT_DIR}/Version.txt --swVer $TF_TFW_VERSION --apiVer $TF_TOOLING_API_VERSION --ref ${CI_COMMIT_SHORT_SHA} --branchName "$CI_COMMIT_REF_NAME"
    - Get-Content ${CI_PROJECT_DIR}/Version.txt

    # Build Tooling
    - cd ${CI_PROJECT_DIR}
    - npm i
    - npm run build:bundle
    # Clean last build
    - cd ${CI_PROJECT_DIR}
    - if (Test-Path -Path "./Tooling_Release") {
      Remove-Item -LiteralPath ./Tooling_Release -Force -Recurse
      Remove-Item -LiteralPath ./Tooling_Release -Force -Recurse
      }
    # Package Tooling
    - mkdir ./Tooling_Release
    - cp ${CI_PROJECT_DIR}/Version.txt ./Tooling_Release
    - cp -R ${CI_PROJECT_DIR}/dist ./Tooling_Release
    - cp -R ${CI_PROJECT_DIR}/Plugins ./Tooling_Release
    - cp -R ${CI_PROJECT_DIR}/quick-start ./Tooling_Release
  artifacts:
    name: 'Tooling_for_Web_Build_${CI_COMMIT_SHORT_SHA}'
    paths:
      - ./Tooling_Release/*
    expire_in: 2 weeks
    when: always

build::docs:
  extends: .Always_Build
  tags:
    - docker-windows
  image: registry.ultrahaptics.com/ooh/infrastructure/windows-touchfree-toolchain:latest
  script:
    - cd ${CI_PROJECT_DIR}
    - npm i
    - npm run build:docs
  artifacts:
    name: 'TouchFree_Tooling_Documentation'
    paths:
      - ./docs/markdown
    expire_in: 2 weeks
    when: always

test:
  extends: .Always_Test
  tags:
    - docker-windows
  image: registry.ultrahaptics.com/ooh/infrastructure/windows-touchfree-toolchain:latest
  script:
    # Run unit tests
    - cd ${CI_PROJECT_DIR}
    - npm i
    - npm run test
    - npm run test:coverage
  artifacts:
    when: always
    name: 'TestResults'
    paths:
      - ${CI_PROJECT_DIR}/junit.xml
      - ${CI_PROJECT_DIR}/coverage/
    reports:
      junit: ${CI_PROJECT_DIR}/junit.xml
      coverage_report:
        coverage_format: cobertura
        path: ${CI_PROJECT_DIR}/coverage/cobertura-coverage.xml
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'

pages:
  stage: deploy
  dependencies:
    - test
  script:
    - mkdir .public
    - cp ${CI_PROJECT_DIR}/coverage/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - develop

package:
  stage: package
  image: alpine:3.13
  dependencies:
    - build::bundle
    - build::docs
  needs: ['build::bundle', 'build::docs']
  script:
    - mkdir ./Tooling_Package/
    - cp -R ./Tooling_Release/* ./Tooling_Package/
    - cp -R ./docs/markdown ./Tooling_Package/Documentation/
  artifacts:
    name: 'TouchFree_Tooling_for_Web_${TF_TFW_VERSION}_${CI_COMMIT_SHORT_SHA}'
    paths:
      - ./Tooling_Package/*
    expire_in: 2 weeks
    when: always
  tags:
    - docker

# npm::publish:
#   stage: deploy
#   when: manual
#   tags:
#     - docker
#   only:
#     - release
#   script:
#     - npm publish

npm::pack:
  extends: .versions
  stage: build
  tags:
    - docker-windows
  image: registry.ultrahaptics.com/ooh/infrastructure/windows-touchfree-toolchain:latest
  when: always
  # only:
  #   - release
  script:
    - npm pack
  artifacts:
    name: 'TouchFree_Tooling_npm_package_${TF_TFW_VERSION}_${CI_COMMIT_SHORT_SHA}'
    paths:
      - touchfree*.tgz
    expire_in: 2 weeks
    
