variables:
  GIT_SUBMODULE_STRATEGY: recursive
  UNITY_EXE: '"C:/Unity/Unity_2019.4.13f1/Editor/Unity.exe"'

stages:
  - build
  - test

# build stage jobs
SC_Service::build:
  stage: build
  when: always
  script:
    - ls ${env:UNITY_EXE}
    - "& ./run_unity_cmd.bat"
  artifacts:
    name: "Screen_Control_Service_${env:CI_COMMIT_SHA}"
    paths:
    - Build/**
    - ./Unity.log
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10

SC_Service::test:
  image: registry.ultrahaptics.com/tools/infrastructure/docker-tools-node-tests:initial_setup
  stage: test

  dependencies:
    - SC_Service::build
  needs: ["SC_Service::build"]

  script:
    - cd ./Testing/ServiceSocketTests/
    - npm install
    - ./node_modules/.bin/gulp build_machine_run
  after_script:
    - if [ -e /build_machine_info.txt ]; then cat /build_machine_info.txt; else echo "No build machine info file"; fi

  artifacts:
    name: test_results
    paths:
      - ./Testing/ServiceSocketTests/results/**
    reports:
      junit: ./Testing/ServiceSocketTests/results/test_results.xml
    when: always
  tags:
    - docker
