variables:
  GIT_SUBMODULE_STRATEGY: recursive
  UNITY_EXE_DIR: 'C:/Unity/2019.4.13f1/Editor'
  UNITY_EXE: 'C:/Unity/2019.4.13f1/Editor/Unity.exe'
  SC_CFW_PATH: $CI_PROJECT_DIR/ScreenControl_Web
  SC_CFU_PATH: $CI_PROJECT_DIR/ScreenControl_Unity/Assets/ScreenControl/Client
  SC_SRV_PATH: $CI_PROJECT_DIR/ScreenControl_Unity/Assets/ScreenControl/Service
  SC_CFU_VERSION: 'alpha3'
  SC_CFW_VERSION: 'alpha3'
  SC_SRV_VERSION: 'alpha3'
  SC_API_VERSION: '1.0.1'

stages:
  - build
  - test

SC_Client::Unity::build:
  stage: build
  when: always
  script:
    # Update Version.txt with latest information before packaging
    - python ./Scripts/UpdateVersionFile.py --path ${env:SC_CFU_PATH}/Version.txt --swVer ${env:SC_CFU_VERSION} --apiVer ${env:SC_API_VERSION} --ref ${env:CI_COMMIT_SHA}
    # Copy Version.txt to Client_Release folder
    - mkdir ./Client_Release
    - cp ${env:CI_PROJECT_DIR}/ScreenControl_Unity/Assets/ScreenControl/Client/Version.txt ./Client_Release
    # Package Client
    - cd ./Scripts
    - "& ./package_unity_client.bat"
  artifacts:
    name: "Screen_Control_Client_for_Unity_${env:SC_CFU_VERSION}_${env:CI_COMMIT_SHA}"
    paths:
      - ./Client_Release/*
      - ./Client_for_Unity_package.log
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10

SC_Client::Web::build:
  stage: build
  when: always
  script:
    # Update Version.txt with latest information before packaging
    - python ./Scripts/UpdateVersionFile.py --path ${env:SC_CFW_PATH}/Version.txt --swVer ${env:SC_CFW_VERSION} --apiVer ${env:SC_API_VERSION} --ref ${env:CI_COMMIT_SHA}
    # Build Client
    - cd ${env:SC_CFW_PATH}
    - npm i
    - ./node_modules/.bin/gulp build
    # Package Client
    - cd ${env:CI_PROJECT_DIR}
    - mkdir ./Client_Release
    - mkdir ./Client_Release/dist
    - cp ${env:SC_CFW_PATH}/Version.txt ./Client_Release
    - cp -r ${env:SC_CFW_PATH}/build/dist ./Client_Release/
  artifacts:
    name: "Screen_Control_Client_for_Web_${env:SC_CFU_VERSION}_${env:CI_COMMIT_SHA}"
    paths:
      - ./Client_Release/*
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10

# build stage jobs
SC_Service::build:
  stage: build
  when: always
  script:
    # Update Version.txt with latest information before packaging
    - python ./Scripts/UpdateVersionFile.py --path ${env:SC_SRV_PATH}/Version.txt --swVer ${env:SC_CFW_VERSION} --apiVer ${env:SC_API_VERSION} --ref ${env:CI_COMMIT_SHA}
    - cp ${env:SC_SRV_PATH}/Version.tx $CI_PROJECT_DIR/Build

    # Update ProjectSettings file with correct version & build service
    - python ./Scripts/UpdateUnityProjVer.py --path ./ScreenControl_Unity/ProjectSettings/ProjectSettings.asset --ver ${env:SC_SRV_VERSION}
    - cd ./Scripts
    - "& ./build_service.bat"

    # Sign the executable with the UltraLeap certificate
    - $cert=Get-ChildItem -Path Cert:\LocalMachine\My -CodeSigningCert
    - ls $CI_PROJECT_DIR/Build
    - Set-AuthenticodeSignature -FilePath $CI_PROJECT_DIR/Build/ScreenControlService.exe -TimestampServer 'http://timestamp.comodoca.com/authenticode' -Certificate $cert
  artifacts:
    name: "Screen_Control_Service_${env:SC_SRV_VERSION}_${env:CI_COMMIT_SHA}"
    paths:
    - Build/**
    - ./Unity.log
    expire_in: 2 weeks
    when: always
  tags:
    - unity
    - win10

SC_Service::test:
  stage: test

  dependencies:
    - SC_Service::build
  needs: ["SC_Service::build"]

  script:
    - cd ./Testing/ServiceSocketTests/
    - npm install
    - ./node_modules/.bin/gulp build_machine_run

  artifacts:
    name: test_results
    paths:
      - ./Testing/ServiceSocketTests/results/**
      - ./Testing/ServiceSocketTests/PUT_TEST_BUILD_IN_HERE/**
    reports:
      junit: ./Testing/ServiceSocketTests/results/test_results.xml
    when: always
  tags:
    - unity
    - win10
